branches:
  except:
    - /^[0-9]/

language: cpp

compiler:
  - gcc

os:
  - linux
  - osx

cache:
  - apt

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - cmake
      - libsqlite3-dev
      - curl
      - libcurl4-openssl-dev
      - libusb-dev
      - zlib1g-dev
      - libssl-dev
      - libudev-dev
      - git
    on:
      os: linux

update-alternatives:
       - install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
       - install /usr/bin/g++ g++ /usr/bin/g++-4.9 50

sources:
      - trusty

before_install:
  - git clone https://github.com/OpenZWave/open-zwave.git
  - ln -s open-zwave open-zwave-read-only
  - git fetch --unshallow

script:
  - (cd open-zwave-read-only; make)
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_LIBRARY_PATH=open-zwave-read-only
  - make
  - tar czf domoticz_${TRAVIS_OS_NAME}_x86_64.tgz domoticz History.txt License.txt domoticz.sh server_cert.pem updatebeta updaterelease --exclude .svn www/ scripts/ Config/
